# Generated by Django 2.0.2 on 2018-04-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ega', '0004_auto_20180411_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments'),
        ),
    ]
