# Generated by Django 2.0.2 on 2018-04-14 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ega', '0005_tournament_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_placeholder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='home_placeholder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='match',
            name='away',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='ega.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='ega.Team'),
        ),
    ]
