# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ega', '0008_auto_20161226_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
