# Generated by Django 4.0.5 on 2022-07-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ega', '0009_egauser_preferences_prediction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='emoji',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
