# Generated by Django 4.1.7

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ega', '0010_team_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='preferences',
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
