# Generated by Django 5.2.14 on 2026-05-13 17:23

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ega', '0011_tournament_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egauser',
            name='preferences',
            field=models.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
