# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0005_auto_20151230_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='extra_data',
            field=models.JSONField(default=dict, verbose_name='extra data'),
        ),
    ]