# Generated by Django 5.2.14 on 2026-05-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('socialaccount', '0007_alter_socialaccount_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialapp',
            name='provider_id',
            field=models.CharField(
                blank=True, max_length=200, verbose_name='provider ID'
            ),
        ),
        migrations.AddField(
            model_name='socialapp',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(max_length=200, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='provider',
            field=models.CharField(max_length=30, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='socialtoken',
            name='app',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='socialaccount.socialapp',
            ),
        ),
    ]
