# Generated by Django 5.2.14 on 2026-05-13 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0002_auto_20150419_1646'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.EmailField(
                db_index=True, max_length=254, verbose_name='email address'
            ),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='email_address',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='account.emailaddress',
                verbose_name='email address',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='emailaddress',
            unique_together={('user', 'email')},
        ),
        migrations.AddConstraint(
            model_name='emailaddress',
            constraint=models.UniqueConstraint(
                condition=models.Q(('primary', True)),
                fields=('user', 'primary'),
                name='unique_primary_email',
            ),
        ),
        migrations.AddConstraint(
            model_name='emailaddress',
            constraint=models.UniqueConstraint(
                condition=models.Q(('verified', True)),
                fields=('email',),
                name='unique_verified_email',
            ),
        ),
    ]
